repos:
  # Linting and Type Checking
  - repo: local
    hooks:
      - id: namespace-check
        name: Check for @yuyu namespace usage
        entry: bash -c 'if grep -r "@yuyu/" apps/ packages/ --include="*.ts" --include="*.js" --include="*.svelte" 2>/dev/null; then echo "❌ Found @yuyu/ imports! Use @lolita-fashion/ instead"; exit 1; fi'
        language: system
        always_run: true
        
      - id: typescript-check
        name: TypeScript type checking
        entry: bun run type-check
        language: system
        files: \.(ts|tsx)$
        always_run: true
        
      - id: eslint-check
        name: ESLint validation
        entry: bun run lint:check
        language: system
        files: \.(ts|js|svelte)$
        always_run: true
        
      - id: build-check
        name: Build validation
        entry: bash -c 'cd apps/web && bun run build && cd ../api && bun run build'
        language: system
        always_run: true
        pass_filenames: false
        
  # Code Quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']