# Game Monitor System Configuration
# High-performance settings optimized for <1 second response time

# Screen capture settings
screen:
  # Trader list region (F1 hotkey)
  trader_list_region:
    x: 100
    y: 200
    width: 600
    height: 400
  
  # Item scan region (F2 hotkey)
  item_scan_region:
    x: 200
    y: 150
    width: 500
    height: 300
  
  # Trader inventory region (F3 hotkey)
  trader_inventory_region:
    x: 300
    y: 250
    width: 700
    height: 500
  
  # Screenshot save path
  screenshot_save_path: "data/screenshots"
  
  # Auto-save screenshots for debugging
  save_screenshots: true
  
  # Screenshot format (png, jpg)
  screenshot_format: "png"

# OCR engine settings  
ocr:
  # Confidence threshold for accepting OCR results
  confidence_threshold: 0.85
  
  # Maximum time to spend on OCR processing (seconds)
  max_processing_time: 0.8
  
  # Use OCR result caching for performance
  use_cache: true
  
  # OCR language packs (install tesseract language packs)
  languages: "eng+rus"
  
  # Region-specific OCR configurations
  region_configs:
    trader_name:
      psm: 8
      whitelist: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-"
    
    quantity:
      psm: 8
      whitelist: "0123456789"
    
    price:
      psm: 8  
      whitelist: "0123456789."
    
    item_name:
      psm: 7
      languages: "eng+rus"
  
  # Image preprocessing settings
  preprocessing:
    enable: true
    contrast_enhancement: true
    noise_reduction: true
    text_region_detection: true

# Data validation settings
validation:
  # Default validation level (permissive, balanced, strict)
  default_level: "balanced"
  
  # Items requiring strict validation
  strict_mode_items:
    - "epic"
    - "legendary"
    - "artifact"
  
  # Auto-approve threshold (skip manual verification)
  auto_approve_threshold: 0.95
  
  # Historical data validation
  use_historical_validation: true
  
  # Suspicious pattern detection
  detect_suspicious_patterns: true

# Performance settings
performance:
  # Maximum total capture time (seconds)
  max_capture_time: 1.0
  
  # Warning threshold for slow operations
  warning_threshold: 0.8
  
  # Enable detailed performance logging
  enable_performance_logging: true
  
  # Enable performance monitoring
  enable_monitoring: true
  
  # Performance alert thresholds
  alert_thresholds:
    slow_capture: 1.0
    low_confidence: 0.7
    high_error_rate: 0.1

# Database settings
database:
  # Database file path
  path: "data/game_monitor.db"
  
  # Connection pool size
  pool_size: 5
  
  # Enable Write-Ahead Logging for performance
  enable_wal: true
  
  # Cache size (pages)
  cache_size: 10000
  
  # Batch operation size
  batch_size: 100
  
  # Auto-cleanup settings
  cleanup:
    # Clean old OCR cache entries (days)
    ocr_cache_days: 7
    
    # Clean old screenshots (days)  
    screenshot_days: 30
    
    # Clean old trade records (days, 0 = never)
    trade_records_days: 0

# Hotkey settings
hotkeys:
  # Hotkey mappings
  mappings:
    trader_list: "F1"
    item_scan: "F2"
    trader_inventory: "F3"
    manual_verification: "F4"
    emergency_stop: "F5"
  
  # Hotkey response settings
  max_queue_size: 100
  processing_timeout: 5.0
  
  # Enable hotkey statistics
  enable_statistics: true

# Logging settings
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR)
  level: "INFO"
  
  # Log file path
  file: "logs/game_monitor.log"
  
  # Max log file size (MB)
  max_size: 50
  
  # Number of backup log files
  backup_count: 5
  
  # Log format
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Enable console logging
  console: true

# GUI settings (future implementation)
gui:
  # Main window settings
  window:
    width: 800
    height: 600
    title: "Game Monitor System"
  
  # Theme settings
  theme: "dark"
  
  # Update intervals (seconds)
  update_intervals:
    statistics: 1.0
    status: 0.5
    logs: 2.0

# Advanced settings
advanced:
  # Thread pool settings
  thread_pool_size: 4
  
  # Memory usage limits
  max_memory_mb: 200
  
  # Enable experimental features
  experimental:
    multi_engine_ocr: false
    ai_enhancement: false
    auto_calibration: false
  
  # Debug settings
  debug:
    save_processed_images: false
    enable_timing_logs: false
    verbose_validation: false