regions:
  item_scan:
    description: Item scan region
    height: 300
    hotkey: F2
    width: 500
    x: 200
    y: 150
  trader_inventory:
    description: Inventory region
    height: 500
    hotkey: F3
    width: 700
    x: 300
    y: 250
  trader_list:
    description: Trader list capture region
    height: 400
    hotkey: F1
    width: 600
    x: 100
    y: 200
