regions:
  item_scan:
    description: Item scan region
    height: 300
    hotkey: F2
    width: 500
    x: 200
    y: 150
  test_region:
    description: Test region for validation
    height: 150
    hotkey: F1
    width: 300
    x: 100
    y: 200
  trader_inventory:
    description: Trader inventory region
    height: 500
    hotkey: F3
    width: 700
    x: 300
    y: 250
  trader_list:
    description: Trader list region
    height: 400
    hotkey: F1
    width: 600
    x: 100
    y: 200
